### ISSUE TITLE
couldn't get the namespace resource, such as role, rolebinding

### ISSUE THREAD

**Issue by jianzhangbjz** [gmeghnag/omc#132]
The namespace's resource `role` isn't stored in the `namespaces` folder, but the `cluster-scoped-resources`. As we can see below, the `role` resource did in there, but the `omc` couldn't get it.
```yaml
jiazha-mac:~ jiazha$ cat must-gather/must-gather.local.1006115980782152064/017d95993583ba00c54c4198f6626e74584f9146dfbc0f6cc5c8d4c09eae1c98/cluster-scoped-resources/operators.coreos.com/operators/amq-broker-rhel8.cluster-tests.yaml |grep -i role -A 3
      kind: Role
      name: amq-broker-operator.v7.1-5HK4JCfzhBY5ZNGXrYHHtv0ig7R5ukbpb1fy92
      namespace: cluster-tests
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      name: amq-broker-operator.v7.1-5HK4JCfzhBY5ZNGXrYHHtv0ig7R5ukbpb1fy92
      namespace: cluster-tests
    - apiVersion: v1

jiazha-mac:~ jiazha$ omc use ~/must-gather/must-gather.local.1006115980782152064/
jiazha-mac:~ jiazha$ omc get role -n cluster-tests
No resources roles.rbac.authorization.k8s.io found in cluster-tests namespace.
jiazha-mac:~ jiazha$ omc get rolebinding -n cluster-tests
No resources rolebindings.rbac.authorization.k8s.io found in cluster-tests namespace.
```
