### ISSUE TITLE
omc failed due to `wrong must-gather file composition`, but omg works well

### ISSUE THREAD

**Issue by jianzhangbjz** [gmeghnag/omc#133]
As follows, the must-gather link: http://10.73.131.57:9000/openshift-must-gather/must-gather-259369-757024088.tar.gz?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=openshift%2F20240122%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240122T192608Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=37ca2ab204e62b95ba27a9819ec06a5c720b45421e2af567492efdef1dcb0610
```yaml
jiazha-mac:must-gather-cs2 jiazha$ omc use ~/Downloads/must-gather-cs2
wrong must-gather file composition for /Users/jiazha/Downloads/must-gather-cs2

jiazha-mac:must-gather-cs2 jiazha$ omc project
Using project "openshift-marketplace" on must-gather "/Users/jiazha/Downloads/must-gather-hypershift".

jiazha-mac:must-gather-cs2 jiazha$ omg use ~/Downloads/must-gather-cs2
Selected must-gather: /Users/jiazha/Downloads/must-gather-cs2/must-gather.local.699971839981869108/quay-io-openshift-release-dev-ocp-v4-0-art-dev-sha256*
            Projects: 67
             API URL: ['https://api.maxu-47628.qe.devcluster.openshift.com:6443']
            Platform: ['OpenStack']
          Cluster ID: ['b847900c-8ed3-498e-9175-74e7d4bbf859']
     Desired Version: ['4.12.47']

     Current Project: openshift-marketplace
jiazha-mac:must-gather-cs2 jiazha$ 
```
